version: "3.7"

services:
  db: 
    image: postgres
    # Variables de configuración de Postgres
    environment:
      - POSTGRES_DB=task-hub
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
    # Enlace entre los puertos locales y del contenedor.
      - 5432:5432

  back:
    build: ./back
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      - DB_HOST=db

  front:
    build: ./front
    ports:
      - 8081:8081

  adminer:
    image: adminer
    ports:
      - 8080:8080



